language: python
python: 
- "2.7"
script: 
- echo "1"
deploy: 
  provider: pypi
  user: hparfr
  password: 
    secure: 1ef9l1DzCsZGYAp6TeqK6fw+IAB/GJyAM4nQwVrU+kzHGFItL50NBRL3GNjPOUscrOWV98jW1k9QJZ40caQQ+oH6WNg3jEIN3FOcERxMyFD3umLe8s/YIxCDWwBoMb1Hc+jhQ5saeUEliUkCFtecMI1WS+6McQHzdGd4+4WL9mWIp89PNdzJQHH9aHPi8fE651zAhE2mKB0TZmga+i82GSd3iHm29SZmo8wfX4vmqR0PcR+m70DVp0ETJQYb4jTdwnhEUE0XPGeGOhGu/wGPflrBZSc2q/YRfCLIQfPCQOa8zI7TfA20Ymy5HzBfE0kEa9s9OkMmelF4b82njUoEUs8Tgx/rtkJpQ7F18Y/mIm7hId64IAOOStpwBROjdwlfNjFRYbx0vBh+3BqpWUzwMFcPEdKbRyJQSo2v76NPWUG7Z7goeVvO/jEN//y3wZVAUojbIYpYULffVnSUHO1OjbzdQx6QlJtoMulntkLe/8jZLMEV1kw1YaL9/NgefFhfPMkOuhdg7EQErhk3hpSsrFV3sfPIULakKmrY2t1CuI3KyI0lEsgpcMt7kS3VzgtNfjK2fbVvG+3uwLAU/TMTad92t3rS6ifeh3U0m1YwJR7vxDjHV/KekptCgYkgvCVi99Jt/aM0cPO11Us9oOGesthJOzxUZZ8s7jnKj0s1mOk=
  distributions: sdist bdist_wheel
  on: 
    tags: true
    branch: master
